<?php


class Etudiant extends Personne
{
    private int $identifiant;

    public function __construct(int $age,string $nom,string $prenom,int $id)
    {
        $this->setAge($age);
        $this->setIdentifiant($id);
        $this->setPrenom(prenom);
        $this->setNom($nom);
    }

    /**
     * @param int $identifiant
     */
    public function setIdentifiant(int $identifiant): void
    {
        $this->identifiant = $identifiant;
    }

    /**
     * @return int
     */
    public function getIdentifiant(): int
    {
        return $this->identifiant;
    }

    public function getAge(): int
    {
        return parent::getAge(); // TODO: Change the autogenerated stub
    }

    public function setAge(int $Age): void
    {
        parent::setAge($Age); // TODO: Change the autogenerated stub
    }

    public function __toString() : string
    {
        return "Bienvenue ".$this->getNom()." ".$this->getPrenom();
    }
}