<?php

class Etudiant extends Personne
{
    private string $identifiant;

    /**
     * Etudiant constructor.
     * @param string $name
     * @param string $lastname
     * @param string $years
     * @param string $identifiant
     */

    public function __construct(string $name, string $lastname, string $years, string $identifiant)
    {
        parent::__construct($name,$lastname,$years);
        $this->identifiant = $identifiant;
    }

    /**
     * @param string $identifiant
     */
    public function setIdentifiant(string $identifiant): void
    {
        $this->identifiant = $identifiant;
    }

    /**
     * @return string
     */
    public function getIdentifiant(): string
    {
        return $this->identifiant;
    }

    public function getAge(): string
    {
        return parent::getAge(); // TODO: Change the autogenerated stub
    }

    public function setAge(string $Age): void
    {
        parent::setAge($Age); // TODO: Change the autogenerated stub
    }

    public function __toString() : string
    {
        return "Bienvenue {$this->getNom()} {$this->getPrenom()} ! Voici ton id {$this->getIdentifiant()}, il te sera utile pour récupérer tes notes ;)";
    }

    public function getNom(): string
    {
        return parent::getNom(); // TODO: Change the autogenerated stub
    }

    public function setNom(string $nom): void
    {
        parent::setNom($nom); // TODO: Change the autogenerated stub
    }

    public function getPrenom(): string
    {
        return parent::getPrenom(); // TODO: Change the autogenerated stub
    }

    public function setPrenom(string $Prenom): void
    {
        parent::setPrenom($Prenom); // TODO: Change the autogenerated stub
    }
}