<?php

namespace MesProduits;

use MesCategories\Categorie;

class Produit extends Categorie
{
    private string $identifiant;
    private string $nom;

    public function __construct(string $categorie,string $identifiant, string $nom)
    {
        parent::__construct($categorie);
        $this->identifiant=$identifiant;
        $this->nom=$nom;
    }

    /**
     * @param string $identifiant
     */
    public function setIdentifiant(string $identifiant): void
    {
        $this->identifiant = $identifiant;
    }

    /**
     * @return string
     */
    public function getIdentifiant(): string
    {
        return $this->identifiant;
    }

    public function setCategorie(string $categorie): void
    {
        parent::setCategorie($categorie); // TODO: Change the autogenerated stub
    }

    public function getCategorie(): string
    {
        return parent::getCategorie(); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $nom
     */
    public function setNom(string $nom): void
    {
        $this->nom = $nom;
    }

    /**
     * @return string
     */
    public function getNom(): string
    {
        return $this->nom;
    }

    public function __toString()
    {
        return $this->identifiant." : " . $this->nom . " est une " . $this::getCategorie();
    }
}